services:
  app:
    image: ghcr.io/doanvuduy170921/nines-shop:latest
    container_name: nineshop-api
    restart: always
    ports:
      - "8081:8080"
    env_file:
      - .env
    volumes:
      - /var/www/nineshop/uploads:/app/uploads
    depends_on:
      - postgres-db
      - redis-server
      - rabbitmq-server
    networks:
      - nineshop-net

  frontend:
    image: ghcr.io/doanvuduy170921/nines-shop-ui:latest
    container_name: nineshop-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - app
    networks:
      - nineshop-net

  postgres-db:
    image: postgres:15-alpine
    container_name: nineshop-postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - nineshop-net

  redis-server:
    image: redis:alpine
    container_name: nineshop-redis
    restart: always
    volumes:
      - redisdata:/data
    networks:
      - nineshop-net

  rabbitmq-server:
    image: rabbitmq:3-management-alpine
    container_name: nineshop-rabbitmq
    restart: always
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    networks:
      - nineshop-net

volumes:
  pgdata:
    driver: local
  redisdata:
    driver: local
  rabbitmqdata:
    driver: local

networks:
  nineshop-net:
    driver: bridge